### PR TITLE
feat: config field exclusion by types

### PR DESCRIPTION
**Pull request by adityathebe**
resolves: https://github.com/flanksource/config-db/issues/356

### CODE REVIEW

**Comment by moshloop** [comment]
@adityathebe can we add a test ?

**Comment by moshloop** [comment]
@adityathebe I think class should be optional on the spec, and if empty default it to the type

**Comment by adityathebe** [comment]
@moshloop Added tests and set default for config class

**Comment by moshloop** [comment]
@adityathebe please rebase

**Pull request merged**
